---
services:
  alloy:
    image: docker.io/grafana/alloy:latest
    container_name: alloy
    hostname: alloy
    restart: always
    ports:
      - 12345:12345
    volumes:
      - data:/etc/alloy/
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]
    networks:
      - secure

networks:
  secure:
    external: true

volumes:
  data:
