---
services:
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    restart: always
    user: 1000:1000
    ports:
      - '3000:3000'
    volumes:
      - /opt/volumes/grafana:/var/lib/grafana
