version: "3"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
     - GF_SERVER_ROOT_URL=https://grafana.mindful-student.net/
#     - GF_INSTALL_PLUGINS=grafana-clock-panel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.mindful-student.net`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=le"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - secure

networks:
  secure:
    external: true

volumes:
  grafana-storage:
