version: '3'

services:
  app:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    ports:
      - 8088:80
    volumes:
      - /mnt/user/appdata/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - PUID=99
      - PGID=100
      - UMASK=022
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.mindful-student.net`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    networks:
      - secure
      
networks:
  secure:
    external: true
