version: '3'

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.mindful-student.net`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=le"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    networks:
      - secure
      
networks:
  secure:
    external: true
