services:
  gollum:
    image: gollumwiki/gollum:master
    restart: always
    ports:
      - "80:4567/tcp"
    volumes:
      - gollum-config:/etc/gollum
      - gollum-www-data:/home/www-data
      - gollum-wikidata:/wiki
    command:
      - "--config=/etc/gollum/config.rb"

volumes:
  gollum-config:
  gollum-www-data:
  gollum-wikidata:
