services:
  gollum:
    image: gollumwiki/gollum:master
    container_name: gollum
    hostname: gollum
    restart: always
    #ports:
    #  - "80:4567/tcp"
    volumes:
      - gollum-config:/etc/gollum
      - gollum-www-data:/home/www-data
      - gollum-wikidata:/wiki
    command:
      - "--config=/etc/gollum/config.rb"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gollum.rule=Host(`gollum.mindful-student.net`)"
      - "traefik.http.routers.gollum.entrypoints=websecure"
      - "traefik.http.routers.gollum.tls.certresolver=le"
      - "traefik.http.services.gollum.loadbalancer.server.port=4567"
    networks:
      - secure

networks:
  secure:
    external: true

volumes:
  gollum-config:
  gollum-www-data:
  gollum-wikidata:
