version: "3"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    hostname: cloudflared
    restart: "no"
    # tunnel run um zu starten
    command: $COMMAND
    volumes:
      - /mnt/user/appdata/cloudflared:/home/nonroot/.cloudflared
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    networks:
      - secure

networks:
  secure:
    external: true
