version: '3'

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    restart: always
    volumes:
      - tailscale:/var/lib # State data will be stored in this directory 
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work 
    cap_add: # Required for tailscale to work 
      - net_admin 
      - sys_module 
    command: tailscale up --login-server https://vpn.mindful-student.net
    privileged: true 
    networks:
      - secure
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      
networks:
  secure:
    external: true

volumes:
  tailscale:
