version: '3'

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    restart: always
    volumes:
      - tailscale:/var/lib # State data will be stored in this directory 
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work 
    cap_add: # Required for tailscale to work 
      - net_admin 
      - sys_module 
    command: tailscaled 
    privileged: true 
    networks:
      - secure
      
networks:
  secure:
    external: true

volumes:
  tailscale:
