version: '3'

services:
  db:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    networks:
      - br0
      
networks:
  br0:
    external: true
