version: '3'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    networks:
      - secure
      
networks:
  secure:
    external: true
