version: '3'

services:
  archivebox:
    image: archivebox/archivebox:dev
    container_name: archivebox
    hostname: archivebox
    command: server --quick-init 0.0.0.0:8000
    volumes:
        - data:/data
    environment:
        - ALLOWED_HOSTS=*                   # restrict this to only accept incoming traffic via specific domain name
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.archivebox.rule=Host(`gringotts.mindful-student.net`)"
      - "traefik.http.routers.archivebox.entrypoints=websecure"
      - "traefik.http.routers.archivebox.tls.certresolver=le"
      - "traefik.http.services.archivebox.loadbalancer.server.port=8000"
    networks:
      - secure

volumes:
  data:

networks:
  secure:
    external: true
