version: '3'

services:
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    hostname: portainer_agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    port:
      - 9001:9001
