version: '3'

services:
  tiddlywiki:
    image: 'elasticdog/tiddlywiki:latest'
    container_name: tiddlywiki
    hostname: tiddlywiki
    restart: unless-stopped
    #ports:
    #  - 3166:3166
    volumes:
      - data:/tiddlywiki
    networks:
      - secure
    command: zettelkasten --listen host=0.0.0.0 port=3166 username=marius password="$PW"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tiddlywiki.rule=Host(`wiki.mindful-student.net`)"
      - "traefik.http.routers.tiddlywiki.entrypoints=websecure"
      - "traefik.http.routers.tiddlywiki.tls.certresolver=le"
      - "traefik.http.services.tiddlywiki.loadbalancer.server.port=3166"

volumes:
  data:

networks:
  secure:
    external: true
